-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.kategoriler
(
    kategoriid integer NOT NULL,
    kategoriad character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT kategoriler_pkey PRIMARY KEY (kategoriid)
);

CREATE TABLE IF NOT EXISTS public.kisilertablosu
(
    id integer NOT NULL,
    ad character varying(50) COLLATE pg_catalog."default",
    soyad character varying(50) COLLATE pg_catalog."default",
    sehir character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT id PRIMARY KEY (id)
        INCLUDE(id)
);

CREATE TABLE IF NOT EXISTS public.magaza
(
    magaza_id integer NOT NULL,
    magaza_adi text COLLATE pg_catalog."default",
    CONSTRAINT magaza_pkey PRIMARY KEY (magaza_id)
);

CREATE TABLE IF NOT EXISTS public.sepetler
(
    sepet_id integer NOT NULL,
    kisi_id integer NOT NULL,
    CONSTRAINT sepetler_pkey PRIMARY KEY (sepet_id)
);

CREATE TABLE IF NOT EXISTS public.siparis
(
    siparis_id integer NOT NULL,
    sepet_id integer NOT NULL,
    durum boolean,
    tarih date,
    siparis_tutar integer,
    CONSTRAINT siparis_pkey PRIMARY KEY (siparis_id)
);

CREATE TABLE IF NOT EXISTS public.urunler
(
    urunid integer NOT NULL,
    urunad character varying(30) COLLATE pg_catalog."default",
    stok integer,
    alisfiyat double precision,
    satisfiyat double precision,
    gorsel character varying(100) COLLATE pg_catalog."default",
    kategori integer,
    magaza_id integer,
    CONSTRAINT urunler_pkey PRIMARY KEY (urunid)
);

ALTER TABLE IF EXISTS public.sepetler
    ADD CONSTRAINT kisi_id FOREIGN KEY (kisi_id)
    REFERENCES public.kisilertablosu (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_kisi_id
    ON public.sepetler(kisi_id);


ALTER TABLE IF EXISTS public.siparis
    ADD CONSTRAINT sepet_id FOREIGN KEY (sepet_id)
    REFERENCES public.sepetler (sepet_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_sepet_id
    ON public.siparis(sepet_id);


ALTER TABLE IF EXISTS public.urunler
    ADD CONSTRAINT magaza_id FOREIGN KEY (magaza_id)
    REFERENCES public.magaza (magaza_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_magaza_id
    ON public.urunler(magaza_id);


ALTER TABLE IF EXISTS public.urunler
    ADD CONSTRAINT urunler_foregin FOREIGN KEY (kategori)
    REFERENCES public.kategoriler (kategoriid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_urunler_foregin
    ON public.urunler(kategori);

END;